# Generated by Django 3.1.6 on 2021-05-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybernm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(null=True, related_name='tournament_player', to='cybernm_app.player', verbose_name='игроки'),
        ),
    ]
