# Generated by Django 3.1.6 on 2021-05-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybernm_app', '0002_tournament_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, related_name='tournament_player', to='cybernm_app.player', verbose_name='игроки'),
        ),
    ]
