# Generated by Django 3.1.6 on 2021-05-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybernm_app', '0004_auto_20210526_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='limitation',
            field=models.CharField(choices=[('1-5lvl', '1-5lvl'), ('5-8lvl', '5-8lvl'), ('9-10lvl', '9-10lvl')], max_length=20),
        ),
    ]
