# Generated by Django 3.1.6 on 2021-06-12 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cybernm_app', '0006_auto_20210612_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='discipline_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discipline_id_fk', to='cybernm_app.discipline', verbose_name='discipline'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_employee_id_fk', to=settings.AUTH_USER_MODEL, verbose_name='employee'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, related_name='tournament_player', to=settings.AUTH_USER_MODEL, verbose_name='players'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('a', 'announced'), ('r', 'run'), ('e', 'finished')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image for tournament'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
