# Generated by Django 3.1.6 on 2021-06-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybernm_app', '0006_auto_20210527_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='social_link',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка на соц. сети'),
        ),
    ]
