# Generated by Django 3.1.6 on 2021-06-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybernm_app', '0007_player_social_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='discipline_name',
            field=models.CharField(choices=[('cs', 'Counter-Strike: Global Offensive'), ('vl', 'Valorant'), ('ff', 'Fifa 2021'), ('d2', 'Dota2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='type',
            field=models.CharField(choices=[('st', 'strategy'), ('sh', 'shooter'), ('sm', 'simulator')], max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='discipline_name',
            field=models.CharField(choices=[('cs', 'Counter-Strike: Global Offensive'), ('vl', 'Valorant'), ('ff', 'Fifa 2021'), ('d2', 'Dota2')], max_length=50),
        ),
    ]
