# Generated by Django 3.1.6 on 2021-06-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybernm_app', '0008_auto_20210610_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='discipline_name',
            field=models.CharField(max_length=50),
        ),
    ]
