# Generated by Django 3.1.6 on 2021-06-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybernm_app', '0009_auto_20210611_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='discipline_name',
        ),
    ]
