# Generated by Django 3.1.6 on 2021-06-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybernm_app', '0010_auto_20210612_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='discipline_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
